---
Name: klosterhof
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'Klosterhof'
File:
  extensions:
    - MyFile
SiteConfig:
  extensions:
    - OpeningHours
    - ContactData
Image:
  extensions:
    - MyImage
Currency:
  currency_symbol: "€"